version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pairwise-databases"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
