version: "3"

services:
  db:
    image: "postgres:11"
    container_name: "pairwise-databases"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - databases:/var/lib/postgresql/data

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    volumes:
      - databases:/data/mongodb

volumes:
  databases:
